### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#11]
Hi Anton, 

Here are the sort options:
-Relevance
-Title (a-z)
-Title (z-a)
-Date (oldest first)
-Date (newest first)

We will be providing solr examples. 

thx,
Rosalie

**Comment by pghorpade** [comment]
Hi Anton,

I have added details about sorting on the wiki page  
https://github.com/pier2marketing/ucla-prrla/wiki/Solr-4.10-Search-and-Browse-Specification

For following sort options
-Relevance
By default solr sorts by relevancy

-Title (a-z)
use "&sort=first_title asc" 
-Title (z-a)
use "&sort=first_title desc" 
-Date (oldest first)
use "&sort=sort_decade asc" 
-Date (newest first)
use "&sort=sort_decade desc" 

let me know if you have questions

thnx,
Parinita Ghorpade
