### ISSUE TITLE
Search within results

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#12]
Hi Anton, 

I apologize for going back on a task.... On the search results page, we had a second search box above the Filters. When I talked with Glenn and told him we had removed it, he told me that that second box was to be for "Search within results". SO.... if possible I'd like to 
1. bring that search box back. 
2. add a label above the box that says: Search within results
3. and add the functionality that whatever the user enters in that search box, it searches the results already retrieved, not the entire set of data. 

Please let me know if this is possible and/or if you have any questions. 

thx, 
Rosalie

**Comment by amereshchuk** [comment]
hi Rosalie,

right now search works as "union", for example you entered "air", you got 100 results, then you entered "chair", you got 50 results, then you entered "air chair", you got 150 results.

you are asking now about "intersection" here, for example you entered "air", you got 100 results, then you entered "chair" you got 50 results, then you entered "air chair", with intersection you will get only result where both "air" and "chair" was found. let's say there are 25 records where "air" and "chair" was found, 25 results was returned.

what if we will still skip second search box but change the logic so it will work as "intersection"?
i think it will cover your requirements with more simple user experience. what do you think about?

Parinita, could you please provide a solr example of search query with "intersection" behavior?

thank you,
Anton
