### ISSUE TITLE
Exhibitions data

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#13]
Hi Anton, 

At this time, can you please take any one of the collections that you have currently in the data and build that out as an individual Exhibition. 

Tasks are to:
1. choose one of the collections from any of the institutions that you have
2. build an exhibition around that collection (attached Glenn's template for reference), so for examples where it says exhibition title, you enter the Collection name and where each record displayed below are the individual items. 
3. implement the scrolling functionality of display, relevance, etc. 

I hope i'm clear, but please let me know if you have questions

thank you, 
Rosalie

![exhibition](https://user-images.githubusercontent.com/30246687/29147935-262a1e98-7d1f-11e7-913b-3ba8c35b1dfe.png)

**Comment by amereshchuk** [comment]
hi Rosalie,

you said 'at this time', does it mean that in the future we will need to grad different data for exhibitions?
if the answer is yes, can we wait for life data and build exhibitions based on real data?

thank you,
Anton

**Comment by rosalieucla** [comment]
Hi Anton, 

In this case, there will not be any real data during this phase of the project so once you put in this one collection then you are done. 

thx, 
Rosalie

**Comment by amereshchuk** [comment]
hi Rosalie,

we have HTML for this functionality, we have done pagination on search already, we have work done on this topic already. i think it will be better for us just do that on real data, sometimes things looks the same, but as the result they are different or slightly different.

thank you for your reply,
Anton

**Comment by amereshchuk** [comment]
hi Rosalie,

done. page with exhibitions shows all collections, when you click on any of them list of items is displayed.

thank you,
Anton
