### ISSUE TITLE
Please add Saida Largaespada to Github account

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#15]
Hi Anton, 

Please add:  Saida Largaespada <sjlargaespada@gmail.com> to the PRRLA github site. She will be working on editing the website copy. 

thank you!
Rosalie

**Comment by amereshchuk** [comment]
hi Rosalie,

this email address is not associated with GitHub account.
please provide GitHub name.

thank you,
Anton

**Comment by rosalieucla** [comment]
Hi anton, 

Saida's github username is: sjlargaespada

thx!
Rosalie

**Comment by amereshchuk** [comment]
hi Rosalie,

added.

thank you,
Anton
