### ISSUE TITLE
Edits to the site

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#16]
Hi anton, 

We reviewed the pages and have some feedback on the pages:

**Search Results page.** 
1. now shows all the fields, just the following fields should display:
-Title
-collection
-Institution
-Author
-date

2. View item at... words on the link should dynamically change based on the institution. Eg if the institution is UCLA, the Link should say, View items at UCLA Library, now it says View item at University of Hong Kong for everything

3. the blue box View item at..: not all caps, it should be initial caps, the box should be thinner

4. Title. If there are several titles, use the first one. AND the font size of the title should be larger

5. Filer names, eg Institutions, Collection, Types, etc should be bolded

6. Clear filters link doesn't clear when there is still a search term in the search box. Let's discuss maybe that is correct??

7. when the results are long, they 'disappear" behind the footer grey. 

Explore collections page
1. The page title "Explore Collection" should be in black and the underline should be centered. 

Banner image
-on Non-home pages: institution, exhibition, search results, PRL collections, etc should be thinner

Page titles
eg. Help, About us, PRL Collections, should be black font and the underline blue centered. 

Translate pull down
Change Javanese to Japanese 

Footer
Change to: Explore Collections

**Comment by amereshchuk** [comment]
hi Rosalie,

all done.

Anton

**Comment by rosalieucla** [comment]
Hi Anton, 

Thank you for all these edits, here are some follow ups, all really minor:
1. SEARCH RESULTS - Title. can you make the font size of the title a font larger 

2. Page titles. eg. Help, About us, PRL Collections, the thin blue underline was perfect before, it was just not centered under the title name, please bring it back to what it was and center it. 

thx!
Rosalie
