### ISSUE TITLE
Search Bar Size

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#20]
Hi Anton,

When looking at Glenn's design I've noticed that our search bar is currently too small. It'd be great if you could make it larger so it is more noticeable. You can see that Glenn's design has a longer and thicker search bar. Here's a comparison of our search bar and Glenn's for reference:

https://ucla.box.com/s/uoy1d7t1zv00zphpndu8w1a7eo2qe05w

Thanks,
Saida

**Comment by sjlargaespada** [comment]
![screen shot 2017-08-21 at 3 04 23 pm](https://user-images.githubusercontent.com/31044167/30296170-0f0ccb14-96f8-11e7-87c2-9cc9f24d0ff0.jpg)

**Comment by Hlopec** [comment]
Hi, please check it.
