### ISSUE TITLE
Search Item details- Thumbnail and text

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#24]
Hi Anton,

When searching for items, within the results, (1)the thumbnails seems too big and there is awkward spacing between the text. (2)The title is also slightly smaller than the ideal size. (3)Also, again please change the "At" in the blue box to a lowercase "at" (i.e. "View Item At University of California Los Angeles" should change to ""View Item at University of California Los Angeles"

This is what it currently looks like: https://ucla.box.com/s/u8gt7phimv0wsj25l6o75uhquuitkd7k

This is what it should look like: https://ucla.box.com/s/3royzdxmtx9iim17knm9ta499vqwvg6n 

Best,
Saida

**Comment by sjlargaespada** [comment]
@amereshchuk, could we get the blue "View Item" blue box to align like Glenn's design: https://ucla.box.com/s/3royzdxmtx9iim17knm9ta499vqwvg6n

thanks!

**Comment by pier2marketing** [comment]
on it!

**Comment by sjlargaespada** [comment]
closing this since it's better explained in issue #39
