### ISSUE TITLE
Display Thumbnail on Search Result and  View Item Pages

### ISSUE THREAD

**Issue by pghorpade** [UCLALibrary/ucla-prrla#27]
Hi Anton,

To show thumbnail for each record on Search Results and View Item Pages,

Follow the instructions on wiki page
https://github.com/pier2marketing/ucla-prrla/wiki/Solr-4.10-Search-and-Browse-Specification#thumbnail

let me know if you have questions

thank you
Parinita Ghorpade

**Comment by sjlargaespada** [comment]
@amereshchuk, here is the chosen "no thumbnail" image.
![prl no thumbnail icon 3-03](https://user-images.githubusercontent.com/31044167/30566823-7da5aa70-9c82-11e7-90c5-20448e2548cd.png)

**Comment by rosalieucla** [comment]
@amereshchuk, Please let us know if you have any questions or need further information. 

thx, 
Rosalie

**Comment by amereshchuk** [comment]
done.
