### ISSUE TITLE
Sort Decade Filter

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#29]
Hi Anton, 
Can you please set the Decade (aka Date) Filter to sort Reverse Chronological. 

eg
2017
2016
2015
etc.

thx, 
Rosalie

**Comment by pier2marketing** [comment]
Hi Rosalie,

This is in process. I'll update the status as soon as it's ready.

Many Thanks,
Paul

**Comment by Hlopec** [comment]
Hi! 
Decade filter sorted.
