### ISSUE TITLE
sort pull down box size

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#30]
Hi Anton,

could we increase the size of the sort pull down box? The text gets cut off as seen here:
<img width="529" alt="screen shot 2017-09-11 at 10 42 00 am" src="https://user-images.githubusercontent.com/31044167/30288556-00d61cf4-96de-11e7-9320-89f8f178e2f5.png">

Thanks,
Saida

**Comment by pier2marketing** [comment]
Hi Saida,

We're on it. I'll update here when ready.

Thanks,
Paul
