### ISSUE TITLE
ng build with prod flag

### ISSUE THREAD

**Issue by kjallen** [UCLALibrary/ucla-prrla#31]
Our team gets several errors when running ng build with --prod flag.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/data/prrladeploy/pier2/ucla-prrla/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

Could you confirm able to build using --prod? Or let us know what is required to build with this option

**Comment by pier2marketing** [comment]
Thank you. Let us investigate and get back to you, please.

**Comment by kjallen** [comment]
Checking in with any updates on this

**Comment by Hlopec** [comment]
please try this.
ng build --env=prod --no-sourcemap

**Comment by cachemeoutside** [comment]
looks like it's working with the --no-sourcemap option

@kjallen can you confirm on your side?

Here's my output:
==
$ node_modules/.bin/ng build --env=prod --no-sourcemap
Hash: 64d94d30695139dd649a
Time: 7665ms
chunk    {0} polyfills.bundle.js (polyfills) 191 kB {4} [initial] [rendered]
chunk    {1} main.bundle.js (main) 141 kB {3} [initial] [rendered]
chunk    {2} styles.bundle.js (styles) 148 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js (vendor) 2.53 MB [initial] [rendered]
chunk    {4} inline.bundle.js (inline) 0 bytes [entry] [rendered]

**Comment by kjallen** [comment]
Confirmed this is working for my local build as well.
