### ISSUE TITLE
Add logo to header

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#32]
Anton, 
Please substitute the PRRLA | PRL header text with the logo 
![prl](https://user-images.githubusercontent.com/31044167/30614074-14691124-9d3f-11e7-9a39-89807d5f8335.png)

Thanks!

**Comment by rosalieucla** [comment]
Hi anton, 

we are going to send out the site for review to some folks, so it would be great if you could to add this logo by Friday, morning PST. 

thx,
Rosalie

**Comment by Hlopec** [comment]
done
