### ISSUE TITLE
Add PRRLA Link to header

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#33]
Anton,
in line 33 of header.component.html Please make the PRRLA in the navigation bar link to pr-rla.org

thanks!

**Comment by rosalieucla** [comment]
Hi anton, 

we are going to send out the site for review to some folks, so it would be great if you could complete this ticket by Friday, morning PST. 

thx,
Rosalie

**Comment by Hlopec** [comment]
done
