### ISSUE TITLE
Re-alphabetize the Institutions Page and get rid of gaps

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#34]
Hi Anton,

Two things:
1. Make sure there aren't any gaps between the names as seen in the image below (between Kansai University Korea University and National Taiwan University)

2. Please re-alphabetize the list of institutions on the Institutions Page? Currently it's alphabetized in rows (left to right). We would like it to be in alphabetical order as columns (top to bottom)

i.e. First column would look something like: 

Beijing Institute of Technology
Chinese University of Hong Kong
City University of Hong Kong
Fudan University
Hong Kong Baptist University
Hong Kong Polytechnic University
Hong Kong University of Science and Technology
Kansai University
Korea University
Nanjing University
National Taiwan University
National University of Singapore
Peking University
Seoul National University

and the next column to the right of these would begin with "Singapore Management University." The last name on the list would be "Zhejiang University" and it would be on the bottom right.

Thanks!
![inst](https://user-images.githubusercontent.com/31044167/30669970-519357fe-9e15-11e7-9169-ca5f1a66b56c.png)

**Comment by Hlopec** [comment]
done
