### ISSUE TITLE
Remove mailto: command from the individual institutions pages

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#35]
Hi Anton,

because not all institutions have contact e-mails, such as UC Irvine, we would like to have you remove all of the the mailto: commands in order to prevent any issues.
![uci](https://user-images.githubusercontent.com/31044167/30670560-9c2b54a4-9e17-11e7-944c-d5f7c247e89b.png)

**Comment by Hlopec** [comment]
done
