### ISSUE TITLE
Left-align University Logos

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#37]
Anton,

Please re-align the University logos to the left. 
![1](https://user-images.githubusercontent.com/31044167/30671435-b9609a1c-9e1b-11e7-8a67-3255dcb18fdf.jpg)

It should look like:
![2](https://user-images.githubusercontent.com/31044167/30671443-bfa65f6a-9e1b-11e7-8102-7df4bff3372c.jpg)

Thanks,
Saida

**Comment by Hlopec** [comment]
done
