### ISSUE TITLE
URLs that contain Solr queries need to be escaped

### ISSUE THREAD

**Issue by kjallen** [UCLALibrary/ucla-prrla#38]
As we have been adding content we've uncovered a few unanticipated bugs. Our latest set of data has some content that contains the ':' character, which looks like cannot be included in a Solr query without being escaped.

`Escaping Special Characters
Lucene supports escaping special characters that are part of the query syntax. The current list special characters are`
\+ - && || ! ( ) { } [ ] ^ " ~ * ? : \
`To escape these character use the \ before the character. For example to search for (1+1):2 use the query:
\(1\+1\)\:2`

We first encountered this in the 'View Details' link. For example if you go to http://test-prl.library.ucla.edu/search?therms=ucla

Then hover over the View Details link (other than first item) you will see the characters not being escaped.

**Comment by amereshchuk** [comment]
done.
