### ISSUE TITLE
Blue 'View Item' button not visible on some items

### ISSUE THREAD

**Issue by kjallen** [UCLALibrary/ucla-prrla#41]
I think this also might be related to rendering of #38, some items do not have a blue 'view item' 

Example search with blue button:

http://test-prl.library.ucla.edu/search?filters=%7B%22institutionName%22:%5B%22University%20of%20Auckland%22%5D%7D

Example search missing blue button:

http://test-prl.library.ucla.edu/search?filters=%7B%22institutionName%22:%5B%22University%20of%20California,%20Los%20Angeles%22%5D%7D

**Comment by amereshchuk** [comment]
we do not show blue button if field identifier_keyword is empty, we use value of this field as url. if empty, button doesn't make sense. right?

**Comment by amereshchuk** [comment]
identifier_keyword returns one or more urls, we grabbed urls wrong. not it fixed. done.
