### ISSUE TITLE
Remove Copyright message for items when viewing details

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#42]
Hi Anton,

Please remove the copyright section in the red circle for **all items**

<img width="1440" alt="screen shot 2017-09-22 at 2 56 27 pm" src="https://user-images.githubusercontent.com/31044167/30766024-6c01f9ea-9fa7-11e7-9e0e-f86bf20824e6.png">

Thanks,
Saida

**Comment by Hlopec** [comment]
done
