### ISSUE TITLE
Populate Search Results metadata fields from Solr document.

### ISSUE THREAD

**Issue by pghorpade** [UCLALibrary/ucla-prrla#44]
Hi Anton ,

For this page currently, the code uses the facet field data .
Change this to populate from solr documents.
The examples are here [Search Results Details](https://github.com/pier2marketing/ucla-prrla/wiki/Solr-4.10-Search-and-Browse-Specification#search-results-record-fields)

let me know if you have questions

**Comment by amereshchuk** [comment]
hello, we have moved back all fields. before we had request to hide fields. please let me know if that works correct now. thank you.

**Comment by rosalieucla** [comment]
see ticket #45.

**Comment by pghorpade** [comment]
Hi @amereshchuk ,

for the following link which we call the search results page

http://test-prl.library.ucla.edu/search?page=1&filters=%7B%7D&therms=&order=

I am seeing more labels and metadata then expected, please look at my documentation https://github.com/pier2marketing/ucla-prrla/wiki/Solr-4.10-Search-and-Browse-Specification#search-results-record-fields
for the  required fields and labels for this page.

also there is another issue created for this particular bug.
#45 

![screen shot 2017-09-26 at 6 27 57 pm](https://user-images.githubusercontent.com/4259468/30891491-8e0217d4-a2e8-11e7-88c7-8acc7d3868ad.png)

Following will outline what is required for each item in result list,

if any of the metadata is missing , like if autthor (creator_keyword) is missing, do not display the label "Author" with n/a value.

**Also following labels do not have any fields in solr document.**

_Alternate Title and First Title. , please remove them from the page_

![screen shot 2017-09-26 at 6 38 03 pm](https://user-images.githubusercontent.com/4259468/30891781-f70db5de-a2e9-11e7-8673-ce1b5e091e0d.png)


Let me know if you have any questions

**Comment by Hlopec** [comment]
done
