### ISSUE TITLE
Remove Extra Metadata from Search Results

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#45]
Hi Anton,

On the search results page we only want:
**Title
Collection
Institution
Author
Date**

Thanks,
Saida

**Comment by rosalieucla** [comment]
@amereshchuk, it would be great if you could fix this for us by Noon our time, tomorrow, 9/27.  

The details of the fields for the search results is documented in Parinita's solr documentation on githhub. 

thx!
Rosalie

**Comment by Hlopec** [comment]
done
