### ISSUE TITLE
Browse by Collections Linking to Search Results of the Entire Institution, not the Individual Collection

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#46]
Hi,

Example: On the [Explore Collections Page](http://test-prl.library.ucla.edu/explore-collections) when you select East Asian Maps In The Bruman Collection [1083] it sends you to:
http://test-prl.library.ucla.edu/search?filters=%7B%22institutionName%22:%5B%22University%20of%20California,%20Los%20Angeles%22%5D%7D

it should go to

http://test-prl.library.ucla.edu/search?page=1&filters=%7B%22institutionName%22:%5B%22University%20of%20California,%20Los%20Angeles%22%5D,%22collectionName%22:%5B%22East%20Asian%20Maps%20in%20the%20Bruman%20Collection%22%5D%7D&therms=&order=

thanks!

**Comment by saslv** [comment]
Done.
