### ISSUE TITLE
UCLA Institution Page Collections

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#47]
For [UCLA's institution page](http://test-prl.library.ucla.edu/institution?name=University%20of%20California%20Los%20Angeles) it currently displays the [**University Of California Los Angeles**](http://test-prl.library.ucla.edu/institution?name=University%20of%20California%20Los%20Angeles) value (doesn't have the comma), please change to 
**University of California, Los Angeles** 

so it shows all of these collections:
http://test-prl.library.ucla.edu/institution?name=University%20of%20California,%20Los%20Angeles

thanks!

**Comment by rosalieucla** [comment]
@amereshchuk  - this is a different, but related issues. Here's an example of an institution with collections but they do not show up on this page: http://test-prl.library.ucla.edu/institution?name=Chinese%20University%20of%20Hong%20Kong

**Comment by saslv** [comment]
Hi!

We are using data from solr via query we where provided to get prrla_members:
http://test-solr.library.ucla.edu/solr/prrla/select?q=prrla_member_title:*&rows=0&wt=json&sort=prrla_member_title%20asc&indent=true&facet=true&facet.field=prrla_member_title&json.wrf=__ng_jsonp__.__req0.finished

In response we don't have names with comma. 
The best way will be to handle this on back-end, but if you will provide a list with corresponding names we can replace them by ourselves on front-end.

**Comment by sjlargaespada** [comment]
@pghorpade thoughts?

**Comment by kjallen** [comment]
This ticket may be closed. The solution we have decided on is to update the data on our end, your queries will stay the same.
