### ISSUE TITLE
View Details Subject Description

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#49]
Currently the subject description field is cut off as seen here:

<img width="840" alt="screen shot 2017-09-26 at 4 24 00 pm" src="https://user-images.githubusercontent.com/31044167/30888788-4456e09e-a2d7-11e7-9f88-c93175044d97.png">

Please keep the column width, but add a line break before the word "description" so it shows as

Subject
Description:

Thanks!

**Comment by Hlopec** [comment]
done
