### ISSUE TITLE
Add Banner words to all pages

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#50]
Hi Anton, 

For our release tomorrow, we just realized that we would like to add a note to each page to remind people that this is a test site. 

Please have the following words: TEST SITE; TEMPORARY, SAMPLE DATA 

If this helps, we found this code:
https://stackoverflow.com/questions/30761750/how-can-i-overlay-a-banner-status-line-on-every-web-page-in-a-test-environment

i'm marking this top priority because we would like this done by tomorrow, 9/27, if possible

thx, 
Rosalie

**Comment by Hlopec** [comment]
done

**Comment by sjlargaespada** [comment]
@Hlopec 
Currently it says "THIS IS DEMO PAGE. ORIGIN PAGE - COMING SOON" not "TEST SITE; TEMPORARY, SAMPLE DATA"

<img width="1440" alt="screen shot 2017-09-27 at 8 50 13 am" src="https://user-images.githubusercontent.com/31044167/30923533-f2dec04e-a360-11e7-9908-aad03cf2f7f6.png">

**Comment by sjlargaespada** [comment]
Fixed
