### ISSUE TITLE
Shorten Title on View Details Page

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#51]
Please limit the top title shown on the viewing details to approximately 60 charters, but make sure it does not cut in the middle of a word

I.e. **Please shorten the title in the red circle,** but keep the green title its original length
<img width="1440" alt="screen shot 2017-09-26 at 6 01 30 pm" src="https://user-images.githubusercontent.com/31044167/30891007-43ab4442-a2e5-11e7-9887-eb9af94bdd2a.png">

**Comment by Hlopec** [comment]
done

**Comment by sjlargaespada** [comment]
@Hlopec Please see issue #52 which may be related to this recent change

**Comment by Hlopec** [comment]
done

**Comment by rosalieucla** [comment]
@Hlopec  thank you for all your work today!!!  This is minor so not a rush.. but we should have the full title completely visible on the "view details' Page for the title in the page, see the screen shot above.. the GREEN circle.  thx!

**Comment by sjlargaespada** [comment]
@Hlopec, please refer to original post so that the the full title shows where I have circled in green. Thanks!

**Comment by Hlopec** [comment]
done, please check it.

**Comment by sjlargaespada** [comment]
yay thanks!!!
