### ISSUE TITLE
Missing Titles

### ISSUE THREAD

**Issue by sjlargaespada** [UCLALibrary/ucla-prrla#52]
Many items are missing titles both in the search results and view items page. For example, the majority of Auckland is missing as seen below:

<img width="1440" alt="screen shot 2017-09-27 at 9 05 46 am" src="https://user-images.githubusercontent.com/31044167/30924421-884e3dec-a363-11e7-95b7-d7a55e6d2685.png">

**Comment by Hlopec** [comment]
fixed
