### ISSUE TITLE
Remove External Links display from View Details page

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#54]
Hi, 

Please remove "external links' field from display on the "view details" page. 

we have now decided it is in fact confusing for the user. 

see screen shot of field. 

thx!
Rosalie
![ext link](https://user-images.githubusercontent.com/30246687/31037688-191843b2-a527-11e7-960d-ac3cac47e412.png)

**Comment by Hlopec** [comment]
done
