### ISSUE TITLE
View Details page - external links and design for view item blue box

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#56]
This is placeholder for work to come

**Comment by markmatney** [comment]
The following changes should be applied to the "View Details" page:
- remove the "External Link(s): ..." entry from the displayed metadata
- change the blue boxed link ("View Item At ...") to point to the URL stored in the `external_link` field in the item's Solr document
- add a list of links underneath the blue boxed link, one per URL stored in the `alternate_external_link` multi-valued field (which may contain 0 or more elements), as shown in the attached screenshot -- if there are no URLs in this field, hide the list of links

We have not made this data available for all collections, but we have done so for the "United College Oracle Bones" collection from "Chinese University of Hong Kong":

http://test-solr.library.ucla.edu/solr/prrla/select?q=collectionName%3A%22United+College+Oracle+Bones%22&wt=json&indent=true

http://test-prl.library.ucla.edu/search?filters=%7B%22collectionName%22:%5B%22United%20College%20Oracle%20Bones%22%5D%7D

**Comment by rosalieucla** [comment]
Hi, Attached is mock up of how it should display. NOTE: that we'd love to have the URLs 'masked' and all say "View Item" vs spelling out the entire URL.


![view item 1](https://user-images.githubusercontent.com/30246687/31104981-802d54aa-a795-11e7-9e37-a621f83be3ab.jpg)

**Comment by Hlopec** [comment]
Please, move alternate_external_link from facet_counts to the response.
Thank you!

**Comment by rosalieucla** [comment]
Hi, 

Just to clarify. If there is only one link (ie nothing in alternate_external_link) then do not display the label: Alternate Links: 

thx!
Rosalie

**Comment by Hlopec** [comment]
Hi @rosalieucla, 
ok, it will be done. Please, move alternate_external_link from facet_counts to the response.

Thank you!
![image](https://user-images.githubusercontent.com/11785317/31333493-fad55704-acf2-11e7-99ba-5e2233f5b3de.png)

**Comment by markmatney** [comment]
@Hlopec we are in the process of adding this field for UCLA's collections -- if you want live test data right now, please see the bottom of [my comment above](https://github.com/pier2marketing/ucla-prrla/issues/56#issuecomment-333701031).

**Comment by markmatney** [comment]
Please let us know as soon as possible if the test data we've provided is not sufficient for you to make progress on this issue.

**Comment by Hlopec** [comment]
Hi @markmatney!
It will be great if all items will have look like this one

http://test-solr.library.ucla.edu/solr/prrla/select?q=collectionName%3A%22United+College+Oracle+Bones%22&wt=json&indent=true

Thank you!

**Comment by markmatney** [comment]
@Hlopec, I've re-indexed the following UCLA collections: 
- East Asian Maps in the Bruman Collection
- Han Yu-Shan Collection
- Tom Leung Collection
- UCLA East Asian Archaeology Corona Satellite Images Collection: 1960s-1970s

We are unable to make this change for many of the other collections since they were indexed in a different way, but the available data is now sufficient to cover all the test cases. You can assume that in production, the `external_link` field will exist in every Solr document that will ever appear on `/search`. Please note that some documents may not have the `alternate_external_link` field, for example http://test-solr.library.ucla.edu/solr/prrla/select?q=collectionKey%3Aeast_asian_maps&wt=json&indent=true.

**Comment by saslv** [comment]
@markmatney done.

**Comment by rosalieucla** [comment]
@saslv , @amereshchuk 

I may not have the latest code, but this does not appear to be working. 

our test case is this link: 
http://test-prl.library.ucla.edu/detail/oai_3Adspace.cityu.edu.hk_3A2031_2F155.xml?s_filters=%7B%22collectionName%22:%5B%22Student%20Works%20With%20External%20Awards%22%5D%7D&s_therms=&s_order=
 	
If the Blue box link on this page goes to the CUHK site, then  it is fixed. 

can you please test this for me

we need to go to production today and this is the last item that is the blocker to that. It would be really great if we can get this resolved this morning. 

thx!
Rosalie

**Comment by rosalieucla** [comment]
here is another test: http://test-prl.library.ucla.edu/detail/oai:scholarspace.manoa.hawaii.edu:10125%2F12722?s_filters=%7B%7D&s_therms=horse&s_order=

thx!

**Comment by saslv** [comment]
@rosalieucla the last link(http://test-prl.library.ucla.edu/detail/oai:scholarspace.manoa.hawaii.edu:10125%2F12722?s_filters=%7B%7D&s_therms=horse&s_order=) will open correct site. (http://hdl.handle.net/10125/12722).

In case if item has no external_link we hide blue button.

**Comment by rosalieucla** [comment]
Hi and thank you, 

Just to be sure....

you are confirming that your latest code,  If I click this link:

http://test-prl.library.ucla.edu/detail/oai:scholarspace.manoa.hawaii.edu:10125%2F12722?s_filters=%7B%7D&s_therms=horse&s_order=

and then click the blue box, it goes to this link:  http://hdl.handle.net/10125/12722 

is that correct?

Rosalie

**Comment by saslv** [comment]
@rosalieucla, yes!

**Comment by markmatney** [comment]
@saslv  I am just comfirming that this seems to be fine. There is a disparity between some of our test Solr records that was causing @rosalieucla to see [this problem](https://github.com/pier2marketing/ucla-prrla/issues/56#issuecomment-336165298). Thanks!
