### ISSUE TITLE
"Search Results" breadcrumb links to incorrect page

### ISSUE THREAD

**Issue by markmatney** [UCLALibrary/ucla-prrla#57]
Please see the page at `/detail/oai_3AGeorge-Grace-Collection_3A1.xml` for example. The breadcrumb link to "Search Results" (top left) doesn't link to the search results page.

Our proposed solution is that whenever a user navigates from `/search` to `/detail`, the `/search` page should pass the current web address to the `/detail` page, which it will link to in the breadcrumb trail:
```
if user arrives at /detail from /search (i.e., /search passed a breadcrumb URL to the /detail page handler):
   link to that URL
else:
   link to a query using institutionName and collectionName, e.g. /search?page=1&filters=%7B%22institutionName%22:%5B%22University%20of%20California%20Los%20Angeles%22%5D,%22collectionName%22:%5B%22Archive%20of%20Popular%20American%20Music%22%5D%7D&therms=&order=
```

**Comment by markmatney** [comment]
I just added some clarification to the description, hopefully it's more clear now.

**Comment by saslv** [comment]
Done.

**Comment by markmatney** [comment]
@saslv, the `else` statement in my pseudo-code above seems to be not implemented. In other words, when arriving at `/detail` from a location other than `/search` (perhaps by opening a link to "View Details" in a new tab in their browser), the "Search Results" breadcrumb currently doesn't do anything useful; in fact, doing so now it breaks the application (for example, try clicking "Search Results" on this page: http://test-prl.library.ucla.edu/detail/oai:scholarspace.manoa.hawaii.edu:10125%2F16012).

The controller/handler for the `/detail` route should already have the required data (Collection Name and Institution Name) in order to create a valid query string for a link back to `/search`.

**Comment by saslv** [comment]
@markmatney, I have fixed url for case if user will open page in new tab. 
In case if we not have params in url it doesn't make sense to show breadcrubms so I have removed them.

**Comment by markmatney** [comment]
Thanks @saslv
