### ISSUE TITLE
Remove + from browse collection page. 

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#60]
Hi, 

There should be no + on this page: http://test-prl.library.ucla.edu/explore-collections

Here's is Glenn's design. the Collection title is bold and the institution name and follows it unbold. 

![prrla__pacific_rim_research_libraries_alliance__project_overview_-_digital_library_program_-_confluence](https://user-images.githubusercontent.com/30246687/31156502-a0d4bd4a-a869-11e7-97c3-748f437b6caf.png)

**Comment by Hlopec** [comment]
"+" - removed
we can't show everything because we get data by sepereted requests

**Comment by rosalieucla** [comment]
Hi @Hlopec, 

Two issues. 
1.  Let me see if I understand, you cannot style the Browse by Collection Title as it is in the attached screen shot? That is, the institution follows after the Collection title, NOT that it appears when you click the collection title. 
If that is the case, Please remove the institution name all together from the Browse by Collection title page. 

2. Can you keep the + on the Browse by Institution page and remove it ONLY from the Browse Collection Title page? 

thx!
-Rosalie

**Comment by Hlopec** [comment]
1 - if we do this as a design, this will increase the loading time of the page.
2 - done

**Comment by rosalieucla** [comment]
Please go ahead and do #1. Even tho it will increase the time. We tested with users and they want to know the institution name as well

Thx

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Hlopec** [comment]
ok, done.
