### ISSUE TITLE
Sort collections lexicographically on /institution and /explore-collections

### ISSUE THREAD

**Issue by markmatney** [UCLALibrary/ucla-prrla#61]
Collections should be sorted lexicographically where they are listed:
- on `/institution`, e.g. http://test-prl.library.ucla.edu/institution?name=University%20of%20Hawaii%20at%20Manoa
- on `/explore-collections`, in the "BROWSE BY INSTITUTION" tab whenever an institution name is expanded using the (+) button

**Comment by saslv** [comment]
Done.
