### ISSUE TITLE
Display "date_keyword" value next to "Date:" label on search results page

### ISSUE THREAD

**Issue by markmatney** [UCLALibrary/ucla-prrla#63]
It looks like each search result's item displays the value of "decade" next to the "Date:" label, which is incorrect. The value of "date_keyword" should be displayed instead. [Just as we decided here](https://github.com/pier2marketing/ucla-prrla/issues/43#issuecomment-333994319), please print each date on its own line.

**Comment by Hlopec** [comment]
done

**Comment by markmatney** [comment]
When I go to `/search?therms=&page=1&filters=%7B%22collectionName%22%3A%5B%22UCLA%20East%20Asian%20Archaeology%20Corona%20Satellite%20Images%20Collection%3A%201960s-1970s%22%5D%2C%22institutionName%22%3A%5B%22University%20of%20California%20Los%20Angeles%22%5D%7D&order=` I get errors in Firefox and Chromium.

**Comment by amereshchuk** [comment]
we print everything as it is for date field. but data is not structured. sometimes it's just year, other case full date, other case array of same datas, etc.
please clarify how to print this field.

thank you.

**Comment by markmatney** [comment]
Dates should be printed in the same way as with [issue 43](https://github.com/pier2marketing/ucla-prrla/issues/43#issuecomment-333619231).

**Comment by markmatney** [comment]
(looks like that's what you're doing now, so I closed this issue)
