### ISSUE TITLE
Different data from Solr after refresh page

### ISSUE THREAD

**Issue by Hlopec** [UCLALibrary/ucla-prrla#68]
Sometimes we have different count of items for the same requests. As the result page will display different collections count, etc. Attached screenshoots.
This is strange because we can just refresh page few times during 5 seconds and response can be different.
Also this hapened in other places.
see https://github.com/pier2marketing/ucla-prrla/issues/56

![image](https://user-images.githubusercontent.com/11785317/31273390-1667cd20-aa97-11e7-807b-25373c0d869c.png)
![image](https://user-images.githubusercontent.com/11785317/31273446-625383b4-aa97-11e7-8213-7daf44a47c70.png)
![image](https://user-images.githubusercontent.com/11785317/31278603-4a86efac-aaae-11e7-8de0-fa7ca2d8c51e.png)

after reload page
![image](https://user-images.githubusercontent.com/11785317/31273415-34b0af9a-aa97-11e7-9bf7-1e2e0b093868.png)
![image](https://user-images.githubusercontent.com/11785317/31273471-843fe5c6-aa97-11e7-8949-0c03af8a3c56.png)
![image](https://user-images.githubusercontent.com/11785317/31278624-5b05b282-aaae-11e7-9958-69770ba0ec45.png)

Thank you!

**Comment by cachemeoutside** [comment]
@Hlopec this is resolved. One of our slaves wasn't polling from the master. Let me know if it works on your end now.

Thanks,

- Anthony

**Comment by Hlopec** [comment]
Thank you!
