### ISSUE TITLE
Make the title in results clickable

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#70]
Hi, 

Sorry to throw one last issue at you, but we just uncovered a usability issue that we would like to have fixed by tomorrow if possible. 

Please make the title in the search results clickable. it should go the same place that the "view details" goes. Here's a screen capture to show which fields I mean. 
thx!
Rosalie 
![results link](https://user-images.githubusercontent.com/30246687/31416045-7f884d88-addb-11e7-9636-531eb135d47d.png)

**Comment by rosalieucla** [comment]
Just to add that the title link would be just like the other links on the site --  blue underline and it turns darker blue when you mouse over it.

**Comment by Hlopec** [comment]
Hi,
I leave "View Details" button and made title like same link. Please look in this.
