### ISSUE TITLE
API message error on search

### ISSUE THREAD

**Issue by kjallen** [UCLALibrary/ucla-prrla#71]
On the latest build we get an API error for any search terms entered.

To replicate go to:
http://test-prl.library.ucla.edu
Enter 'hawaii'
You will see Backend error Problems with API. Try to reload page.

Or may go to:
http://test-prl.library.ucla.edu/search?therms=hawaii

**Comment by rosalieucla** [comment]
This seems odd but the search appears to only give an error when you search words that are in the  institution's name. Is that possible? A coincidence? 

we need to go production today and this new bug is a blocker. Is there any way that someone can take a look at this? 

thx, 
Rosalie

**Comment by amereshchuk** [comment]
we will take a look now.

**Comment by markmatney** [comment]
Rosalie has made an excellent observation. That is exactly the issue that I'm seeing. It seems as though this issue can be mostly be reproduced by visiting `/institutions` and trying to perform a search where the search terms are found in any institution name: for example "university of hawaii", "university of", "university", "chinese stanford", "of california", "singapore barbara".

However, some searches don't follow this pattern: "university of fdsa" contains a word not in any institution name, and gives an error.

Examples that don't give an error: "universit", "yooniversity", "yooniversity hawai", "hawai universiiii".

**Comment by markmatney** [comment]
(you don't have to be on the institutions page for any reason other than to see search terms to try)

**Comment by pghorpade** [comment]
hi @amereshchuk ,

I have some more details for this issue, 

if I search on "hawaii" or  "beijing" solr returns member institution record in the first 10 results.

http://solr.library.ucla.edu/solr/prrla/select?q=hawaii&rows=10&start=0&wt=json&sort=&facet=true&facet.field=institutionName&facet.field=collectionName&facet.field=type_keyword&facet.field=creator_keyword&facet.field=decade&facet.field=language_keyword&facet.field=rights_keyword&facet.field=collection&facet.field=source_keyword&facet.field=description_keyword&facet.field=identifier_keyword&facet.field=thumbnail_url&facet.field=title_keyword&facet.field=subject_keyword&facet.field=publisher_keyword&facet.field=contributor_keyword&facet.field=date_keyword&facet.field=alternate_external_link&facet.field=format_keyword&facet.field=relation_keyword&facet.field=coverage_keyword&indent=true

http://solr.library.ucla.edu/solr/prrla/select?q= beijing&rows=10&start=0&wt=json&sort=&facet=true&facet.field=institutionName&facet.field=collectionName&facet.field=type_keyword&facet.field=creator_keyword&facet.field=decade&facet.field=language_keyword&facet.field=rights_keyword&facet.field=collection&facet.field=source_keyword&facet.field=description_keyword&facet.field=identifier_keyword&facet.field=thumbnail_url&facet.field=title_keyword&facet.field=subject_keyword&facet.field=publisher_keyword&facet.field=contributor_keyword&facet.field=date_keyword&facet.field=alternate_external_link&facet.field=format_keyword&facet.field=relation_keyword&facet.field=coverage_keyword&indent=true

Please ignore these records when displaying the search results.

The json solr doc for member institution looks like the following

```
{
        "id":"University of Hawaii at Manoa",
        "prrla_member_title":"University of Hawaii at Manoa",
        "prrla_member_description":"Our faculty and staff serve as the human connection between people and the knowledge\nresources that they need to succeed. We acquire, organize, preserve, and provide access to\ninformation resources and are active partners in the University’s mission to promote information\nliteracy. The Library provides a sustainable learning environment that meets the space,\ncomputing, and information needs of the UHM academic community. The Library is a premier\nresource for Hawaii, Pacific and Asia-related research. It facilitates access to knowledge\nthroughout the world and contributes unique content to global networked information resources.",
        "prrla_member_location":"United States",
        "prrla_member_email":"library@hawaii.edu",
        "prrla_member_phone":"808-956-7205",
        "prrla_member_website":"http://library.manoa.hawaii.edu/",
        "prrla_member_latitude":"157°48'58.4\"W (-157.816210)",
        "prrla_member_longitude":"21°18'02.6\"N (21.300724)",
        "_version_":1580529980964601857},
```

**Comment by kjallen** [comment]
This makes sense, basically the institution records do not follow the same format as an item (they have different fields etc...) so it would not fit into the item display template.

As @pghorpade mentions, please exclude institution records from the search results pages, as they will cause errors if looking for fields that don't exist. The institution solr documents do not have the same fields as the dublin_core/item documents

**Comment by saslv** [comment]
Done.

**Comment by rosalieucla** [comment]
thank you!!! done.
