### ISSUE TITLE
Transfer ownership of ucla-prrla to UCLA

### ISSUE THREAD

**Issue by kjallen** [UCLALibrary/ucla-prrla#76]
Ownership should be transferred to the uclalibrary repository group, with owner of kjallen

**Comment by Hlopec** [comment]
Hi Krisian, 
we can transfer ownership to you, but what acectly mean uclalibrary repository group?
![screen shot 2017-12-13 at 3 09 59 pm](https://user-images.githubusercontent.com/11785317/33940562-19a0d174-e018-11e7-97a1-53bf1ed491f0.png)
Thank you!

**Comment by markmatney** [comment]
Hi @Hlopec,

Kristian means that the "New owner's GitHub username or organization name" should be `UCLALibrary`.

**Comment by Hlopec** [comment]
Hi @markmatney, @kjallen 
I tried transfer this repository but I have this message:
UCLALibrary already has a repository in the pier2marketing/ucla-prrla network and You don’t have the permission to create repositories on UCLALibrary.

**Comment by kjallen** [comment]
This has been addressed, woohoo
