### ISSUE TITLE
PRRLA Institutions Spreadsheet: Logo, Address, Description

### ISSUE THREAD

**Issue by rosalieucla** [UCLALibrary/ucla-prrla#9]
Hi Anton, 

Here's the spreadsheet with the PRRLA institutions info. 

Here's the link: https://docs.google.com/spreadsheets/d/1M_0TeagEfI_KB-ivQFyDWBpgUBZqUKifDtkTgubjouA/edit?usp=sharing

You will see that some data is missing, i've put [coming soon] as a holder place, I will add that data later, please load it as it is. 

Regarding the logo, i included a file for each logo (attached here into github). If I could also include a link to a website I put that  in also in case that was easier for you.  

You will see that there is a latitude and longitude column in the spreadsheet, please ignore. 

Please let me know if you have any questions, i'm in the office this Thursday and Friday. 

thx!!
Rosalie

![chinese university of hong kong](https://user-images.githubusercontent.com/30246687/28905871-7e9f12a6-77c8-11e7-9df7-d9d5a3b797c8.png)
![zhejiang university](https://user-images.githubusercontent.com/30246687/28905870-7e9e7224-77c8-11e7-873f-9d8ab0e998ea.png)
![wuhan university](https://user-images.githubusercontent.com/30246687/28905873-7ea0f472-77c8-11e7-9062-4b80c1a64619.jpg)
![university of washington](https://user-images.githubusercontent.com/30246687/28905872-7ea0e752-77c8-11e7-832a-b3bcb36cbaea.png)
![university of victoria](https://user-images.githubusercontent.com/30246687/28905874-7ea390d8-77c8-11e7-874d-addc5331a095.jpg)
![university of sydney](https://user-images.githubusercontent.com/30246687/28905875-7ea48e5c-77c8-11e7-9dcc-299745b12eda.png)
![university of southern california](https://user-images.githubusercontent.com/30246687/28905876-7eb35ec8-77c8-11e7-8b20-9d9da11ef171.jpg)
![university of otago](https://user-images.githubusercontent.com/30246687/28905877-7eb4b70a-77c8-11e7-94be-19811ba4b6f2.jpg)
![university of oregon](https://user-images.githubusercontent.com/30246687/28905878-7eb5c71c-77c8-11e7-8439-a19313fc544e.png)
![university of melbourne](https://user-images.githubusercontent.com/30246687/28905879-7eb6db0c-77c8-11e7-8e4f-770c8b3083e1.png)
![university of macau](https://user-images.githubusercontent.com/30246687/28905880-7eb8c25a-77c8-11e7-8c30-059d022776ad.png)
![universitas indonesia](https://user-images.githubusercontent.com/30246687/28905881-7eb8f446-77c8-11e7-95da-0f04f7a1df85.png)
![university of hong kong](https://user-images.githubusercontent.com/30246687/28905882-7ec80e7c-77c8-11e7-954a-f5a2a998c720.png)
![university of hawaii at manoa](https://user-images.githubusercontent.com/30246687/28905883-7eca0380-77c8-11e7-80f5-441db33bc55f.jpg)
![university of california santa barbara](https://user-images.githubusercontent.com/30246687/28905884-7eca5182-77c8-11e7-897e-b02e9b1c1df3.png)
![university of california san diego](https://user-images.githubusercontent.com/30246687/28905885-7eccd5b0-77c8-11e7-8d8a-732feb52de55.png)
![university of california merced](https://user-images.githubusercontent.com/30246687/28905887-7ecee5e4-77c8-11e7-83de-7b93d58e7d3c.png)
![university of california los angeles](https://user-images.githubusercontent.com/30246687/28905886-7ecd8dfc-77c8-11e7-94c8-dc2059785530.jpg)
![university of california irvine](https://user-images.githubusercontent.com/30246687/28905888-7eddc276-77c8-11e7-8842-7103a378953b.jpg)
![university of california berkeley](https://user-images.githubusercontent.com/30246687/28905889-7edfa69a-77c8-11e7-9c44-c3e5a7a5be94.png)
![university of british columbia](https://user-images.githubusercontent.com/30246687/28905890-7ee08b6e-77c8-11e7-9f49-4ce7952c21d2.png)
![university of auckland](https://user-images.githubusercontent.com/30246687/28905891-7ee0c7c8-77c8-11e7-9794-c3d6490e6587.jpg)
![tsinghua university](https://user-images.githubusercontent.com/30246687/28905892-7ee1f594-77c8-11e7-99af-8046d5328421.gif)
![tohoku university](https://user-images.githubusercontent.com/30246687/28905894-7ef78012-77c8-11e7-970b-18af48d21523.png)
![sun yat-sen university](https://user-images.githubusercontent.com/30246687/28905893-7ef21bc2-77c8-11e7-8d3a-62060da6af9b.gif)

![singapore_management_university_logo svg](https://user-images.githubusercontent.com/30246687/28905896-7ef7bdac-77c8-11e7-963c-69568ac4426a.png)
![seoul national university](https://user-images.githubusercontent.com/30246687/28905895-7ef7b28a-77c8-11e7-8aa1-9c394e19da05.jpg)
![peking_university_seal svg](https://user-images.githubusercontent.com/30246687/28905897-7ef80c80-77c8-11e7-9c26-13fe794dd9ec.png)
![national university of singapore](https://user-images.githubusercontent.com/30246687/28905903-7f19d662-77c8-11e7-9c16-6f8829150b4d.png)
![national taiwan university](https://user-images.githubusercontent.com/30246687/28905898-7f0dd9e8-77c8-11e7-9e2d-56b92a5c318f.png)
![nanjing_university_logo svg](https://user-images.githubusercontent.com/30246687/28905899-7f105150-77c8-11e7-8ddf-d258e7c7e8de.png)
![kansai university](https://user-images.githubusercontent.com/30246687/28905900-7f106136-77c8-11e7-9c5a-497de403e44e.jpg)
![korea university](https://user-images.githubusercontent.com/30246687/28905901-7f106fa0-77c8-11e7-8d14-203ef1aba698.gif)
![hong kong university of science and technology](https://user-images.githubusercontent.com/30246687/28905902-7f10c61c-77c8-11e7-9f90-49f7940d3631.png)
![hong kong polytechnic university](https://user-images.githubusercontent.com/30246687/28905904-7f21f7ca-77c8-11e7-8376-96b8bb2b2946.png)
![hong kong baptist university](https://user-images.githubusercontent.com/30246687/28905906-7f292374-77c8-11e7-8aa1-934185113a50.png)
![beijing institute of technology](https://user-images.githubusercontent.com/30246687/28905905-7f2837ac-77c8-11e7-9052-295530f90961.gif)
![fudon university](https://user-images.githubusercontent.com/30246687/28905907-7f294034-77c8-11e7-98f6-6e8099ab9789.png)
![city university of hong kong](https://user-images.githubusercontent.com/30246687/28905908-7f299c78-77c8-11e7-8d7d-67e79a3caae4.png)

**Comment by amereshchuk** [comment]
Hi Rosalie,

I thought we have to grab institutions by this url http://test-solr.library.ucla.edu/solr/prrla/select?q=*%3A*&rows=0&wt=json&indent=true&facet=true&facet.field=institutionName and grab additional information from spreadsheet you attached.

But spreadsheet contains more institutions, does it mean that we build page based on spreadsheet and grab collections for institutions that exist in solr, for the rest nothing display in collection lists?

Thank you,
Anton

**Comment by rosalieucla** [comment]
HI Anton,

What I do know is that you do not have the total dataset, you have a subset. So yes, there should be more institutions on my list. But I don’t know what to do about that now. I’ve forwarded your question to Parinita so I will get back to you when I get an answer.

Thx!
Rosalie

**Comment by rosalieucla** [comment]
Anton,

So that we keep everything in github issues I’ll respond now there for this item.

-Rosalie

**Comment by rosalieucla** [comment]
oops, I'm clearly learning github issues, I didn't realize it went directly here. that's great!!!

Here's the latest on spreadsheet:
We have decided on a process (we will put the institutions into solr), so for you, do not implement a system of reading from the spreadsheet, once we have the solr we will send you the code/info that you need. We will get that to you by August 21, maybe sooner.  

For now, it would be great if you could hard code in 5 institutions to see how it displays

AND
If an institutions does not have any collections, keep the collection Label, but add these words where the collections would go:
No collections are currently available

**Comment by amereshchuk** [comment]
hi Rosalie,

can we wait for live data and than build that?
is there any reason to hard code and then build again based on live data?
i would like to avoid rebuild if possible.

thank you,
Anton

**Comment by rosalieucla** [comment]
Hi Anton, 

Yes, it would be ok to wait until we give you the live data. thank you for asking. 

--Rosalie

**Comment by pghorpade** [comment]
Hi Anton,

To get the complete list of prrla members you can use

following 2 ways

you can get the list from the facet filed prrla_member_title

http://test-solr.library.ucla.edu/solr/prrla/select?q=prrla_member_title:*&rows=0&wt=json&indent=true&facet=true&facet.field=prrla_member_title

or from the docs field

http://test-solr.library.ucla.edu/solr/prrla/select?q=prrla_member_title:*&fl=prrla_member_title&rows=40&wt=json&indent=true

Once user clicks a member on the listing page

you can use following solr queries to populate text on the  Individual Member Page

http://test-solr.library.ucla.edu/solr/prrla/select?q=prrla_member_title:%22University%20of%20California%20Los%20Angeles%22&wt=json&indent=true

the collection list for the individual  member can be fetched with following  query
http://test-solr.library.ucla.edu/solr/prrla/select?q=institutionName:%22University%20of%20California%20Los%20Angeles%22&rows=-1&facet=true&facet.field=collectionName&facet.sort=count&facet.mincount=1&facet.limit=-1


Let me know if you any questions.

Thnx
Parinita

**Comment by rosalieucla** [comment]
Hi Anton, 

I think that you have what you need to implement the institutions page and individual institution 'home pages', (see parinita's message above), please let us know if you need further info and/or have questions. 

thx, 
Rosalie
